### ISSUE TITLE
Assigments will reload

### ISSUE THREAD

**Issue by star1954** [alexwaitz/pomodoro-planner#11]
After an assignment is completed, it will be removed from paired_data. However, the assignment data will be restored when the tab is re-opened as the assignment will remain in localstorage to be accessed next time.

**Comment by rumboogy** [comment]
I know what's going on. I can take care of this.

Essentially, what's going on is that the `localStorage` object gets loaded into the program, but after that list gets edited, it doesn't re-save to `localStorage`. It should be an easy fix.

**Comment by star1954** [comment]
Fixed by commit: 70c9939483aa82950f810ab3f35ab76e56441327
